### ISSUE TITLE
Convert 2016 general town & precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ma#1]
If you want to work on a town, add a comment saying which one you'd like to work on or email openelections@gmail.com. You can either email us finished CSV files or submit a pull request, whatever is easiest. 

The results files you'll be converting can be found [here](https://github.com/openelections/openelections-sources-ma/tree/master/2016). Most of these are either PDFs files, and in some cases you'll need to convert a number of office-specific files. For electronic PDFs, we recommend using [Tabula](http://tabula.technology/), which is free, to extract data. The goal is to create a single CSV file for each county, with the following headers:

`county`, `town`, `precinct`, `office`, `district`, `party`, `candidate`, `votes`

The file name format for the CSV results should be: 

`20161108__ma__general__{town}__precinct.csv`

- [x] Acton
- [ ] Arlington
- [ ] Auburn
- [x] Barnstable
- [x] Belmont
- [ ] Brookline
- [ ] Cambridge
- [x] Chelmsford
- [ ] Danvers
- [x] Dedham
- [x] Falmouth
- [ ] Fitchburg
- [x] Freetown
- [ ] Gloucester
- [ ] Hingham
- [ ] Lexington
- [ ] Lynn
- [ ] Malden
- [ ] Melrose
- [ ] Middleborough
- [ ] Millbury
- [ ] Needham
- [ ] North Andover
- [ ] Natick
- [ ] Plymouth
- [x] Somerset
- [ ] Somerville
- [x] Spencer
- [ ] Walpole
- [ ] Worcester

**Comment by JoeYerardi** [comment]
I'm handling Natick.

**Comment by JoeYerardi** [comment]
Handling Needham, North Andover, Somerset, Spencer and Walpole.

**Comment by JoeYerardi** [comment]
Handling Hingham, Lexington, Lynn, Melrose and Millbury.

**Comment by JoeYerardi** [comment]
Handling Malden, Middleborough, Plymouth, Somerville and Worcester.

**Comment by JoeYerardi** [comment]
Handling Fitchburg, Freetown and Gloucester.

**Comment by JoeYerardi** [comment]
Handling Acton, Barnstable, Belmont and Chelmsford.

**Comment by JoeYerardi** [comment]
Handling Arlington, Auburn, Brookline and Cambridge.

**Comment by dwillis** [comment]
Hey all (especially @eric-famiglietti) - many thanks for your hard work on converting these files. It looks like the state election results site has the same elements, so I'm going to fill in the remainder of the towns and close this issue.
